#%RAML 1.0
---

title: Pull Notifications
version: 1.0
protocols: [ HTTPS ]
baseUri: https://api.service.hmrc.gov.uk/
mediaType: [ application/xml ]

uses:
  sec: https://developer.service.hmrc.gov.uk/api-documentation/assets/common/modules/securitySchemes.raml
  annotations: https://developer.service.hmrc.gov.uk/api-documentation/assets/common/modules/annotations.raml
  types: https://developer.service.hmrc.gov.uk/api-documentation/assets/common/modules/types.raml

documentation:
  - title: Overview
    content: !include docs/overview.md
  - title: Versioning
    content: !include https://developer.service.hmrc.gov.uk/api-documentation/assets/common/docs/versioning.md
  - title: Errors
    content: !include https://developer.service.hmrc.gov.uk/api-documentation/assets/common/docs/errors.md
  - title: Testing
    content: !include docs/testing.md

/notifications:
    /conversationId:
      /{conversationId}:
        uriParameters:
          conversationId:
            description: Conversation identifier UUID
            type: string
            example: "1446a875-eaa1-4d7a-903e-0604166d9557"
        get:
          displayName: Get all notifications for a conversation (trade test only)
          description: Get a list of all notification identifiers for the given conversation identifier (trade test only).
          headers:
            Accept:
              description: Specifies the version of the API that you want to call. See [versioning](/api-documentation/docs/reference-guide#versioning).
              type: string
              required: true
              example: application/vnd.hmrc.1.0+xml
          securedBy: [ sec.x-application ]
          responses:
            200:
              body:
                application/xml:
                  description: Valid XML Payload
                  example: |
                    <resource href="/notifications/conversationId/4cdc771e-c77a-438f-b293-e11ac4cc4e2e/">
                        <link rel="self" href="/notifications/conversationId/4cdc771e-c77a-438f-b293-e11ac4cc4e2e"/>
                        <link rel="notification" href="/notifications/unpulled/7ab99957-b138-4f09-888e-ab4e8107bbe0"/>
                        <link rel="notification" href="/notifications/pulled/1b941d3a-84cd-4127-a80f-36fa1f019359"/>
                    </resource>
        /unpulled:
          /:
          get:
            displayName: Get unpulled notifications for a conversation (trade test only)
            description: Get a list of unpulled notification identifiers for the given conversation identifier (trade test only)
            headers:
              Accept:
                description: Specifies the version of the API that you want to call. See [versioning](/api-documentation/docs/reference-guide#versioning).
                type: string
                required: true
                example: application/vnd.hmrc.1.0+xml
            securedBy: [ sec.x-application ]
            responses:
              200:
                body:
                  application/xml:
                    description: Valid XML Payload
                    example: |
                      <resource href="/notifications/unpulled/">
                          <link rel="self" href="/notifications/unpulled/"/>
                          <link rel="notification" href="/notifications/unpulled/7ab99957-b138-4f09-888e-ab4e8107bbe0"/>
                      </resource>

        /pulled:
          /:
          get:
            displayName: Get pulled notifications for a conversation (trade test only)
            description: Get a list of pulled notification identifiers for the given conversation identifier (trade test only)
            headers:
              Accept:
                description: Specifies the version of the API that you want to call. See [versioning](/api-documentation/docs/reference-guide#versioning).
                type: string
                required: true
                example: application/vnd.hmrc.1.0+xml
            securedBy: [ sec.x-application ]
            responses:
              200:
                body:
                  application/xml:
                    description: Valid XML Payload
                    example: |
                      <resource href="/notifications/pulled/">
                          <link rel="self" href="/notifications/pulled/"/>
                          <link rel="notification" href="/notifications/pulled/7ab99957-b138-4f09-888e-ab4e8107bbe0"/>
                      </resource>
    /unpulled:
      /:
      get:
        displayName: Get unpulled notifications
        description: Get a list of unpulled notification identifiers for the subscribed application
        headers:
          Accept:
            description: Specifies the version of the API that you want to call. See [versioning](/api-documentation/docs/reference-guide#versioning).
            type: string
            required: true
            example: application/vnd.hmrc.1.0+xml
        securedBy: [ sec.x-application ]
        responses:
          200:
            body:
              application/xml:
                description: Valid XML Payload
                example: |
                  <resource href="/notifications/unpulled/">
                      <link rel="self" href="/notifications/unpulled/"/>
                      <link rel="notification" href="/notifications/unpulled/7ab99957-b138-4f09-888e-ab4e8107bbe0"/>
                  </resource>
      /{notificationId}:
        uriParameters:
          notificationId:
            description: Notification identifier UUID
            type: string
            example: "3851c039-107a-42c9-94a9-180893e5f0d5"
        get:
          displayName: Get an unpulled notification
          description: Get an unpulled notification with the given notification identifier
          headers:
            Accept:
              description: Specifies the version of the API that you want to call. See [versioning](/api-documentation/docs/reference-guide#versioning).
              type: string
              required: true
              example: application/vnd.hmrc.1.0+xml
          securedBy: [ sec.x-application ]
          responses:
            200:
              body:
                application/xml:
                  description: Valid XML Payload
                  example: |
                    <?xml version="1.0" encoding="UTF-8"?>
                    <_2:MetaData xmlns:_2="urn:wco:datamodel:WCO:DocumentMetaData-DMS:2"><_2:WCODataModelVersionCode>3.6</_2:WCODataModelVersionCode><_2:WCOTypeName>RES</_2:WCOTypeName><_2:ResponsibleCountryCode/><_2:ResponsibleAgencyName/><_2:AgencyAssignedCustomizationCode/><_2:AgencyAssignedCustomizationVersionCode/><_2_1:Response xmlns:_2_1="urn:wco:datamodel:WCO:RES-DMS:2">
                          <_2_1:FunctionCode>03</_2_1:FunctionCode>
                          <_2_1:FunctionalReferenceID>0f3ec64eec704999995ddf5a3ca9cc0b</_2_1:FunctionalReferenceID>
                          <_2_1:IssueDateTime>
                            <_2_2:DateTimeString formatCode="304" xmlns:_2_2="urn:wco:datamodel:WCO:Response_DS:DMS:2">20190220165953Z</_2_2:DateTimeString>
                          </_2_1:IssueDateTime>
                          <_2_1:Error>
                            <_2_1:ValidationCode>CDS12014</_2_1:ValidationCode>
                            <_2_1:Pointer>
                              <_2_1:DocumentSectionCode>42A</_2_1:DocumentSectionCode>
                              <_2_1:TagID>D013</_2_1:TagID>
                            </_2_1:Pointer>
                          </_2_1:Error>
                          <_2_1:Error>
                            <_2_1:ValidationCode>CDS12015</_2_1:ValidationCode>
                            <_2_1:Pointer>
                              <_2_1:DocumentSectionCode>42A</_2_1:DocumentSectionCode>
                              <_2_1:TagID>D014</_2_1:TagID>
                            </_2_1:Pointer>
                          </_2_1:Error>
                          <_2_1:Declaration>
                            <_2_1:FunctionalReferenceID>gq8lPty99999NLgUQMSAmg</_2_1:FunctionalReferenceID>
                            <_2_1:ID>19GB20GF2F99999VR4</_2_1:ID>
                            <_2_1:RejectionDateTime>
                              <_2_2:DateTimeString formatCode="304" xmlns:_2_2="urn:wco:datamodel:WCO:Response_DS:DMS:2">20190220165953Z</_2_2:DateTimeString>
                            </_2_1:RejectionDateTime>
                            <_2_1:VersionID>1</_2_1:VersionID>
                          </_2_1:Declaration>
                        </_2_1:Response>
                    </_2:MetaData>
            400:
              body:
                application/xml:
                  description: Invalid XML Payload
                  example: |
                      <?xml version="1.0" encoding="UTF-8"?>
                      <errorResponse>
                        <code>BAD_REQUEST</code>
                        <message>Notification is unpulled</message>
                      </errorResponse>
            404:
              body:
                application/xml:
                  description: Invalid XML Payload
                  example: |
                      <?xml version="1.0" encoding="UTF-8"?>
                      <errorResponse>
                        <code>NOT_FOUND</code>
                        <message>Resource was not found</message>
                      </errorResponse>

    /pulled:
      /:
      get:
        displayName: Get pulled notifications
        description: Get a list of pulled notification identifiers for the subscribed application
        headers:
          Accept:
            description: Specifies the version of the API that you want to call. See [versioning](/api-documentation/docs/reference-guide#versioning).
            type: string
            required: true
            example: application/vnd.hmrc.1.0+xml
        securedBy: [ sec.x-application ]
        responses:
          200:
            body:
              application/xml:
                description: Valid XML Payload
                example: |
                  <resource href="/notifications/pulled/">
                      <link rel="self" href="/notifications/pulled/"/>
                      <link rel="notification" href="/notifications/pulled/7ab99957-b138-4f09-888e-ab4e8107bbe0"/>
                  </resource>
      /{notificationId}:
        uriParameters:
          notificationId:
            description: Notification identifier UUID
            type: string
            example: "3851c039-107a-42c9-94a9-180893e5f0d5"
        get:
          displayName: Get a pulled notification
          description: Get a pulled notification with the given notification identifier
          headers:
            Accept:
              description: Specifies the version of the API that you want to call. See [versioning](/api-documentation/docs/reference-guide#versioning).
              type: string
              required: true
              example: application/vnd.hmrc.1.0+xml

          securedBy: [ sec.x-application ]
          responses:
            200:
              body:
                application/xml:
                  description: Valid XML Payload
                  example: |
                    <?xml version="1.0" encoding="UTF-8"?>
                    <_2:MetaData xmlns:_2="urn:wco:datamodel:WCO:DocumentMetaData-DMS:2"><_2:WCODataModelVersionCode>3.6</_2:WCODataModelVersionCode><_2:WCOTypeName>RES</_2:WCOTypeName><_2:ResponsibleCountryCode/><_2:ResponsibleAgencyName/><_2:AgencyAssignedCustomizationCode/><_2:AgencyAssignedCustomizationVersionCode/><_2_1:Response xmlns:_2_1="urn:wco:datamodel:WCO:RES-DMS:2">
                          <_2_1:FunctionCode>03</_2_1:FunctionCode>
                          <_2_1:FunctionalReferenceID>0f3ec64eec704999995ddf5a3ca9cc0b</_2_1:FunctionalReferenceID>
                          <_2_1:IssueDateTime>
                            <_2_2:DateTimeString formatCode="304" xmlns:_2_2="urn:wco:datamodel:WCO:Response_DS:DMS:2">20190220165953Z</_2_2:DateTimeString>
                          </_2_1:IssueDateTime>
                          <_2_1:Error>
                            <_2_1:ValidationCode>CDS12014</_2_1:ValidationCode>
                            <_2_1:Pointer>
                              <_2_1:DocumentSectionCode>42A</_2_1:DocumentSectionCode>
                              <_2_1:TagID>D013</_2_1:TagID>
                            </_2_1:Pointer>
                          </_2_1:Error>
                          <_2_1:Error>
                            <_2_1:ValidationCode>CDS12015</_2_1:ValidationCode>
                            <_2_1:Pointer>
                              <_2_1:DocumentSectionCode>42A</_2_1:DocumentSectionCode>
                              <_2_1:TagID>D014</_2_1:TagID>
                            </_2_1:Pointer>
                          </_2_1:Error>
                          <_2_1:Declaration>
                            <_2_1:FunctionalReferenceID>gq8lPty99999NLgUQMSAmg</_2_1:FunctionalReferenceID>
                            <_2_1:ID>19GB20GF2F99999VR4</_2_1:ID>
                            <_2_1:RejectionDateTime>
                              <_2_2:DateTimeString formatCode="304" xmlns:_2_2="urn:wco:datamodel:WCO:Response_DS:DMS:2">20190220165953Z</_2_2:DateTimeString>
                            </_2_1:RejectionDateTime>
                            <_2_1:VersionID>1</_2_1:VersionID>
                          </_2_1:Declaration>
                        </_2_1:Response>
                    </_2:MetaData>
            400:
              body:
                application/xml:
                  description: Invalid XML Payload
                  example: |
                      <?xml version="1.0" encoding="UTF-8"?>
                      <errorResponse>
                        <code>BAD_REQUEST</code>
                        <message>Notification is unpulled</message>
                      </errorResponse>
            404:
              body:
                application/xml:
                  description: Invalid XML Payload
                  example: |
                      <?xml version="1.0" encoding="UTF-8"?>
                      <errorResponse>
                        <code>NOT_FOUND</code>
                        <message>Resource was not found</message>
                      </errorResponse>

    /:
      get:
        displayName: Get all available notifications (deprecated)
        description: |
          *This endpoint has been deprecated. It will be removed in a future release.*



          Get a list of all notification identifiers for the subscribed application.
        headers:
          Accept:
            description: Specifies the version of the API that you want to call. See [versioning](/api-documentation/docs/reference-guide#versioning).
            type: string
            required: true
            example: application/vnd.hmrc.1.0+xml

        securedBy: [ sec.x-application ]
        responses:
          200:
            body:
              application/xml:
                description: Valid XML Payload
                example: |
                  <resource href="/notifications/">
                      <link rel="self" href="/notifications/"/>
                      <link rel="notification" href="/notifications/7ab99957-b138-4f09-888e-ab4e8107bbe0"/>
                  </resource>

    /{id}:
      delete:
        displayName: Retrieve and delete a notification from the queue (deprecated)
        description: |
          *This endpoint has been deprecated. It will be removed in a future release.*



          Get a notification with the given notification identifier. The notification will be returned in the response body and then deleted from the queue.
        headers:
          Accept:
            description: Specifies the version of the API that you want to call. See [versioning](/api-documentation/docs/reference-guide#versioning).
            type: string
            required: true
            example: application/vnd.hmrc.1.0+xml

        securedBy: [ sec.x-application ]
        responses:
          200:
            body:
              application/xml:
                description: The saved message
                example: |
                  <example>
                    Saved Message
                  </example>
          404:
